name: 'Common Setup'
description: "Internal action for common setup across jobs"
# NOTE timeout-minutes *cannot* bet set within a action and must be set at the root level
runs:
  using: 'composite'
  steps:
    # NOTE cannot run checkout in this local action, must be run by the parent action
    # mise can rarely get stuck installing. It normally takes < 10s to install, so this should never be more than a minute
    - uses: jdx/mise-action@v2
      with:
        version: 2025.1.4
    # TODO document: https://github.com/actions/runner-images/issues/4849, https://github.com/actions/runner-images/issues/264
    - uses: tecolicom/actions-use-apt-tools@v1
      with:
        tools: zsh libnss3-tools
    # without any additional options, this simply installs the latest version of the cli
    - uses: 1password/load-secrets-action@v2
    - uses: iloveitaly/github-action-direnv-load-and-mask@master
      with:
        environment_allowlist: PYTHON_TEST_SERVER_HOST,JAVASCRIPT_SERVER_HOST,VITE_PYTHON_URL,OPENAPI_JSON_PATH
    # cache node_modules
    - uses: actions/cache@v4
      with:
        path: web/node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('web/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-node-modules
