# localias config file syntax
#
# 	alias: port
#
# for example,
#
#   bareTLD: 9003 # serves over https and http
#   implicitly_secure.test: 9002 # serves over https and http
#   https://explicit_secure.test: 9000 # serves over https and http
#   http://explicit_insecure.test: 9001 # serves over http only
#
web.localhost: 8202
api.web.localhost: 8200
api-test.web.localhost: 8201
flower.web.localhost: 8203
api.python-template.localhost: 8200
postgres.python-template.localhost: 51402
redis.python-template.localhost: 51403
mailpit.python-template.localhost: 51404
