"""
Factories to quickly generate both test and dev data.

Polyfactory is powerful, but dangerous. Make sure you understand the nuances of how it works with pydantic
models.
"""

from polyfactory import Ignore, Use
from typeid import TypeID

from activemodel.pytest.factories import ActiveModelFactory
from app.models.user import CLERK_OBJECT_PREFIX, User


class UserFactory(ActiveModelFactory[User]):
    # NOTE this ID is not a TypeIDTYpe so it cannot be autogenerated
    clerk_id = Use(lambda: str(TypeID(CLERK_OBJECT_PREFIX)))

    api_key = Ignore()

    @classmethod
    def post_build(cls, model):
        model.generate_api_key()
        return model
