from app.env import env

from .environments import is_productionish

NO_COLOR = env.bool("NO_COLOR", False)
"supports NO_COLOR standard: https://no-color.org/"

# this is used by the react router url generator and effectively asserts that this var exists
BASE_URL = env.str("BASE_URL")

# BUILD_COMMIT is autogenerated for you if you use the build scripts in this template
# you'll need to set it manually if you're not using the build scripts
if is_productionish():
    BUILD_COMMIT = env.str("BUILD_COMMIT")
else:
    BUILD_COMMIT = "dev"

WEBHOOK_ENDPOINT = env.str("WEBHOOK_ENDPOINT", default=None, validate=None)
