from app.env import env

from .environments import is_productionish, python_environment

NO_COLOR = env.bool("NO_COLOR", False)
"supports NO_COLOR standard: https://no-color.org/"

BASE_URL = env.str("BASE_URL")
"used by the react router url generator and effectively asserts that this var exists"

JAVASCRIPT_CLIENT_BUILD_DIR = env.str(
    "JAVASCRIPT_CLIENT_BUILD_DIR",
    # in non-production, this path is different depending on the environment the JS is built in
    default=f"web/build/{python_environment()}/client",
)
"location of the SPA build, used by the server to serve the static files for the frontend"

# BUILD_COMMIT is autogenerated for you if you use the build scripts in this template
# you'll need to set it manually if you're not using the build scripts
if is_productionish():
    BUILD_COMMIT = env.str("BUILD_COMMIT")
else:
    BUILD_COMMIT = "dev"

WEBHOOK_ENDPOINT = env.str("WEBHOOK_ENDPOINT", default=None, validate=None)
"can remove if the webhook system isn't used"
