from decouple import config

from .environments import is_productionish

NO_COLOR = config("NO_COLOR", cast=bool, default=False)
"supports NO_COLOR standard: https://no-color.org/"

# this is used by the react router url generator and effectively asserts that this var exists
BASE_URL = config("BASE_URL")

# BUILD_COMMIT is autogenerated for you if you use the build scripts in this template
# you'll need to set it manually if you're not using the build scripts
if is_productionish():
    BUILD_COMMIT = config("BUILD_COMMIT", cast=str)
else:
    BUILD_COMMIT = "dev"
