"""add_service_token_to_user

Revision ID: 8f5dbc1f07ba
Revises: 0782ae000489
Create Date: 2025-11-28 13:28:39.461374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import activemodel


# revision identifiers, used by Alembic.
revision: str = '8f5dbc1f07ba'
down_revision: Union[str, None] = '0782ae000489'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'service_token',
               existing_type=sa.UUID(),
               comment='new column for zero-downtime rename of api_key',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'service_token',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='new column for zero-downtime rename of api_key',
               existing_nullable=True)
    # ### end Alembic commands ###
