"""base_models

Revision ID: 45cb46f82351
Revises: 489aff797e2e
Create Date: 2025-11-03 13:25:49.877935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import activemodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45cb46f82351'
down_revision: Union[str, None] = '489aff797e2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('normal', 'admin', name='userrole').create(op.get_bind())
    op.create_table('user',
    sa.Column('id', activemodel.types.typeid.TypeIDType(prefix='usr'), nullable=False, comment='TypeID with prefix: usr'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('clerk_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='external ID of the user in Clerk'),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='email address of the user in Clerk, makes it easy to debug and find users'),
    sa.Column('role', postgresql.ENUM('normal', 'admin', name='userrole', create_type=False), nullable=False, comment='role of the user, primarily to support superuser switching'),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True, comment='last time the user had an active session'),
    sa.Column('api_key', activemodel.types.typeid.TypeIDType(prefix='sk_live'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey'))
    )
    op.create_index(op.f('user_api_key_idx'), 'user', ['api_key'], unique=True)
    op.create_index(op.f('user_clerk_id_idx'), 'user', ['clerk_id'], unique=True)
    op.create_table('webhook_event',
    sa.Column('id', activemodel.types.typeid.TypeIDType(prefix='wh'), nullable=False, comment='TypeID with prefix: wh'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('destination', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='HTTP endpoint that will receive the webhook POST'),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment="application event name (e.g. 'ticket.paid') used for routing/observability"),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='JSON body sent to destination as the POST request payload'),
    sa.Column('failed_at', sa.DateTime(), nullable=True, comment='timestamp of the last failed delivery attempt'),
    sa.Column('succeeded_at', sa.DateTime(), nullable=True, comment='timestamp when delivery last succeeded (used to prevent resends)'),
    sa.Column('originating_id', sa.Uuid(), nullable=True, comment='identifier of the domain object this event refers to, if any'),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON body received from the destination as the POST response payload'),
    sa.PrimaryKeyConstraint('id', name=op.f('webhook_event_pkey')),
    comment='Represents an outbound webhook queued for delivery.'
    )
    op.create_index(op.f('webhook_event_originating_id_idx'), 'webhook_event', ['originating_id'], unique=False)
    op.create_index(op.f('webhook_event_type_idx'), 'webhook_event', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('webhook_event_type_idx'), table_name='webhook_event')
    op.drop_index(op.f('webhook_event_originating_id_idx'), table_name='webhook_event')
    op.drop_table('webhook_event')
    op.drop_index(op.f('user_clerk_id_idx'), table_name='user')
    op.drop_index(op.f('user_api_key_idx'), table_name='user')
    op.drop_table('user')
    sa.Enum('normal', 'admin', name='userrole').drop(op.get_bind())
    # ### end Alembic commands ###
