"""initial_commit

Revision ID: bd93b08d387a
Revises: 
Create Date: 2025-02-08 08:57:25.499344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import activemodel


# revision identifiers, used by Alembic.
revision: str = 'bd93b08d387a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_response',
    sa.Column('id', activemodel.types.typeid.TypeIDType(prefix='llr'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='the AI model used to generate the response'),
    sa.Column('response', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='sha of the hash for easily retrieving the exact same prompt'),
    sa.PrimaryKeyConstraint('id'),
    comment='Model to cache LLM responses for caching and debugging'
    )
    op.create_table('user',
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', activemodel.types.typeid.TypeIDType(prefix='usr'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('clerk_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='external ID of the user in Clerk'),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='email address of the user in Clerk, makes it easy to debug and find users'),
    sa.Column('role', sa.Enum('normal', 'admin', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('llm_response')
    # ### end Alembic commands ###
