"""initial_commit

Revision ID: 7c1c1ea02e20
Revises: 
Create Date: 2025-03-04 15:34:06.617622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import activemodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c1c1ea02e20'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('normal', 'admin', name='userrole').create(op.get_bind())
    op.create_table('llm_response',
    sa.Column('id', activemodel.types.typeid.TypeIDType(prefix='llr'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='the AI model used to generate the response'),
    sa.Column('response', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='sha of the hash for easily retrieving the exact same prompt'),
    sa.PrimaryKeyConstraint('id', name=op.f('llm_response_pkey')),
    comment='Model to cache LLM responses for caching and debugging'
    )
    op.create_table('user',
    sa.Column('id', activemodel.types.typeid.TypeIDType(prefix='usr'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('clerk_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='external ID of the user in Clerk'),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='email address of the user in Clerk, makes it easy to debug and find users'),
    sa.Column('role', postgresql.ENUM('normal', 'admin', name='userrole', create_type=False), nullable=False, comment='role of the user, primarily to support superuser switching'),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True, comment='last time the user had an active session'),
    sa.Column('api_key', activemodel.types.typeid.TypeIDType(prefix='sk_live'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey'))
    )
    op.create_index(op.f('user_api_key_idx'), 'user', ['api_key'], unique=True)
    op.create_index(op.f('user_clerk_id_idx'), 'user', ['clerk_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('user_clerk_id_idx'), table_name='user')
    op.drop_index(op.f('user_api_key_idx'), table_name='user')
    op.drop_table('user')
    op.drop_table('llm_response')
    sa.Enum('normal', 'admin', name='userrole').drop(op.get_bind())
    # ### end Alembic commands ###
