[settings]
lockfile = true
pipx.uvx = true

# this can be done through direnv, but we intentionally manage all PATH mutations through mise to avoid
# conflicts between the bash hooks across different tools.
python.uv_venv_auto = "create|source"
