terraform {
  required_providers {
    # when changing provider versions, you must run `tofu init`
    azurerm = {
      source = "hashicorp/azurerm"
      # azurerm gets updates quite often! Check this page for the latest version:
      # https://github.com/hashicorp/terraform-provider-azurerm/blob/main/CHANGELOG.md
      version = "~> 4.72.0"
    }

    azuread = {
      source  = "hashicorp/azuread"
      version = "~> 3.0.2"
    }

    # required to work around azure provider limitations
    azapi = {
      source  = "Azure/azapi"
      version = "~> 2.9.0"
    }

    # to sync credentials to 1password that are generated by azure setup
    onepassword = {
      source  = "1password/onepassword"
      version = "~> 3.3.1"
    }

    # extract secrets from 1password via direnv
    external = {
      source  = "hashicorp/external"
      version = "~> 2.3.5"
    }

    dokku = {
      # https://github.com/aaronstillwell/terraform-provider-dokku
      source = "aaronstillwell/dokku"
    }

    ssh = {
      source  = "loafoe/ssh"
      version = "~> 2.7.0"
    }
  }

  # NOTE this must be hidden initially to bootstrap the account!
  # backend "azurerm" {
  # # Variables here cannot reference created resources and must only reference local variables.
  # resource_group_name = local.tfstate.resource_group
  # # this must be globally unique across all azure accounts. letters only!
  # storage_account_name = local.tfstate.storage_account
  # container_name       = local.tfstate.container
  # key                  = local.tfstate.key
  # }
}

provider "onepassword" {
  # > "service_account_token" and "account" are set. Please use only one of them.
  # without this the OP_ACCOUNT password will be picked up and conflict with the OP_SERVICE_ACCOUNT_TOKEN, which is not what we want
  account = null
  # service_account_token = null
}

provider "azurerm" {
  # a subscription (aka account) is a account ID, this is the `id` field on the `az account list`
  subscription_id = local.azure_subscription_id

  # # Disable auto-registration to allow explicit azurerm_resource_provider_registration for EncryptionAtHost
  resource_provider_registrations = "none"

  features {
    # skip_provider_registration = true
  }
}
