# NOTE yml config so we can use comments

ignores:
  - isbot
  - react-router-devtools
  - react-icons
  # linting
  - "@trivago/prettier-plugin-sort-imports"
  - prettier
  - "prettier-plugin-tailwindcss"
  # referenced in eslint.config.js
  - "@typescript-eslint/eslint-plugin"
  # test
  - "@vitest/coverage-v8"
  # shadcn / styling
  - postcss
  - autoprefixer
  - "@tailwindcss/typography"
  - "@tailwindcss/forms"
  - tw-animate-css
  - tailwindcss
  - tw-animate-css
  # misc
  - "@sentry/vite-plugin"
  - "~"
ignorePatterns:
  - playground.ts
specials:
  - eslint
  - prettier
