import pluginReact from "eslint-plugin-react"
import reactHooks from "eslint-plugin-react-hooks"
import globals from "globals"
import tseslint from "typescript-eslint"

import pluginJs from "@eslint/js"

export default [
  // 1. Global Ignores
  {
    ignores: [
      "build",
      ".react-router",
      "playground.ts",
      // autogenerated client
      "client",
      // generated by shadcn and should be untouched
      "app/components",
    ],
  },

  // 2. Global Settings and Language Options
  {
    languageOptions: { globals: globals.browser },
    settings: { react: { version: "detect" } },
  },

  // 3. Core Recommended Configurations
  pluginJs.configs.recommended,
  ...tseslint.configs.recommended,

  // 4. React Plugin Configuration (JSX Runtime for React 17+)
  pluginReact.configs.flat["jsx-runtime"],

  // 5. React Hooks and Compiler Configuration
  reactHooks.configs.flat["recommended-latest"],

  // 6. Custom Rule Overrides
  {
    // Ensure these overrides apply to the relevant file types
    files: ["**/*.{js,mjs,cjs,ts,jsx,tsx}"],
    rules: {
      // https://typescript-eslint.io/rules/no-unused-vars/
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          args: "all",
          argsIgnorePattern: "^_",
          caughtErrors: "all",
          caughtErrorsIgnorePattern: "^_",
          destructuredArrayIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          ignoreRestSiblings: true,
        },
      ],
    },
  },
]
