import pluginReact from "eslint-plugin-react"
import reactCompiler from "eslint-plugin-react-compiler"
import reactHooks from "eslint-plugin-react-hooks"
import globals from "globals"
import tseslint from "typescript-eslint"

import pluginJs from "@eslint/js"

export default tseslint.config(
  {
    files: ["**/*.{js,mjs,cjs,ts,jsx,tsx}"],
  },
  {
    ignores: [
      "build",
      ".react-router",
      "playground.ts",
      // autogenerated client
      "client",
      // generated by shadcn and should be untouched
      "app/components",
    ],
  },
  { languageOptions: { globals: globals.browser } },
  pluginJs.configs.recommended,
  ...tseslint.configs.recommended,
  // important change from the default
  {
    // for React 17+, should be default in the future
    ...pluginReact.configs.flat["jsx-runtime"],
    // TODO will be default in the future, must define for now
    settings: { react: { version: "detect" } },
  },
  reactCompiler.configs.recommended,
  reactHooks.configs["recommended-latest"],
  // https://typescript-eslint.io/rules/no-unused-vars/
  {
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          args: "all",
          argsIgnorePattern: "^_",
          caughtErrors: "all",
          caughtErrorsIgnorePattern: "^_",
          destructuredArrayIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          ignoreRestSiblings: true,
        },
      ],
    },
  },
)
