allowBuilds:
  '@clerk/shared': true
  '@sentry/cli': true
  core-js: true
  esbuild: true
  protobufjs: true
onlyBuiltDependencies:
  - '@clerk/shared'
  - '@sentry/cli'
  - '@tailwindcss/oxide'
  - core-js
  - esbuild
  - protobufjs
