allowBuilds:
  '@clerk/shared': true
  '@sentry/cli': true
  core-js: true
  esbuild: true
  protobufjs: true
  '@tailwindcss/oxide': true

# npm-check-updates does NOT respect the default (as of pnpm 11 and ncu 22.2.0)
minimumReleaseAge: 1440
engineStrict: true
